### ISSUE TITLE
Tracking RaySession in downstream package repositories

### ISSUE THREAD

**Issue by luzpaz** [Houston4444/RaySession#218]
[![Packaging status](https://repology.org/badge/vertical-allrepos/raysession.svg?columns=3&header=RaySession)](https://repology.org/project/raysession/versions)

### Todo

- [ ] Alpine
- [ ] FreeBSD https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=282701
- [ ] Gentoo
- [ ] Mageia
- [ ] openmamba
- [ ] openmandriva `https://github.com/OpenMandrivaAssociation/distribution`
- [ ] OpenSUSE 
- [ ] Solus https://github.com/getsolus/packages

**Comment by trebmuh** [comment]
+ LibraZiK, always up to date with regards to RaySession :sunglasses:

**Comment by Houston4444** [comment]
Thanks for this initiative. Note that for some distributions, some repositories exist with a fresher version.
* **Librazik4**, based on Debian bullseye (there is no package for raysession in debian official repos, sadly)
* **Ubuntu Studio backport repository**, based on Ubuntu
* **GeekosDaw**, based on OpenSuse

**Comment by luzpaz** [comment]
Opened 2 tickets for FreeBSD and OpenMandriva
